### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by Tech4Wellness** [sarapis/orservices#121]
I am struggling to wrap my head around how to get this app running on my computer. Can anyone provide a video tutorial or step by step written one? 

Thank you to whoever can

**Comment by royappa** [comment]
Hi, it took a little fiddling but I got it working. The key thing was to install php 7.4, it is not ready for PHP 8.x.

Then something like these, on Ubuntu:
```
apt install php7.4-curl
apt install php7.4-common
apt install php7.4-curl
apt install php7.4-gd
apt install php7.4-mysql
apt install php7.4-zip
apt install unzip
``` 

Then the steps in the instructions (see the README or the home page of the project) starting with "composer -W update" (I added the "-W". 

In the apache config file you have to add this to make it use the .htaccess file
```
    <Directory /var/www/dir>
        AllowOverride all
    </Directory>
```

I had to run "chown -R www-data:www-data storage" on the storage folde to let the webserver write it.
Also as other issues here said, I first loaded the "/database/dump/18102020.sql" and THEN run the php artisan steps listed. 
The "db:seed" information loads an admin user, then you need to go to "yoursite.com/login" to login.

It was not an easy install for me, but for someone with Linux/PHP project experience it should be easy enough, and as of Jan 2024 it DOES seem to generally work and it seems to be a very nice system. We are now adding data.

**Comment by d9it** [comment]
This software is now compatible with PHP 8 and higher versions. 

@Tech4Wellness If you are still experiencing issues running this app on your computer, please inform us so we can assist you in getting started.
