### ISSUE TITLE
Possibly missing database seed data

### ISSUE THREAD

**Issue by royappa** [sarapis/orservices#125]
These tables are in 18102020.sql but not in 09112021.sql:

`airtablekeyinfos`
`all_languages`
`auto_sync_airtables`
`contact_types`
`countries`
`facility_types`
`hsds_api_keys`
`languages`
`maps`
`organization_types`
`religions`
`users`

I have extracted the missing data from the former and put into this attached file so it can be loaded separately. Especially useful is the initial admin user record. Not sure if this type of thing should be raised as an issue, or if the developers want me to do a code change and submit a PR. 

[dat_sql.txt](https://github.com/sarapis/orservices/files/13907752/dat_sql.txt)

**Comment by d9it** [comment]
This has been fixed now. We have updated the latest DB SQL. Please import it.
