### ISSUE TITLE
Crash on loading database dump

### ISSUE THREAD

**Issue by royappa** [sarapis/orservices#128]
Hello, I am testing the latest version (v5.0) with the HSDS changes, with a fresh install. 

1) There was a database crash at the "php artisan db:seed", I have fixed this in my fork, here is the commit hash.

https://github.com/sarapis/orservices/commit/5e3653dfc4d13d71ea21b515767a9f7c7d6e29f1

I can submit a pull request if you like.

2) Unfortunately  I can't complete the install because I get a crash when loading any of the database dump tables, e.g.:
```
 mysql -u ors -p ors < database/dump/09112021.sql
Enter password:
ERROR 1050 (42S01) at line 30: Table 'accessibilities' already exists
```

Could you please upload a new database to the database/dump that is compatible with the latest version? Thanks!

**Comment by royappa** [comment]
I went ahead and created a PR in case you wished to use it. Thanks.

**Comment by d9it** [comment]
We have updated the SQL database in the database folder. Please import the dump and inform us if you encounter any issues.
