### ISSUE TITLE
Crash due to analytics table empty

### ISSUE THREAD

**Issue by royappa** [sarapis/orservices#131]
Hi, I loaded the database dump 06032024.sql successfully, thanks, and am now trying to start the site.
I have had no errors with composer.

Now I am getting the attached crash:
<img width="958" alt="crash_analytics" src="https://github.com/sarapis/orservices/assets/905287/9f46bb73-2d7c-4099-a043-9449fdc45563">

A little debugging shows that the "analytics" table is empty, from where $analytics is set.
I was going to try just inserting some dummy data to get past this, but looking at the structure of the table, there is no "body" column in the table.

Are we maybe missing a migration where that column was added? Thanks.

```
mysql> select * from analytics;
Empty set (0.00 sec)

mysql> describe analytics;
+----------------+--------------+------+-----+-------------------+-----------------------------------------------+
| Field          | Type         | Null | Key | Default           | Extra                                         |
+----------------+--------------+------+-----+-------------------+-----------------------------------------------+
| id             | int unsigned | NO   | PRI | NULL              | auto_increment                                |
| search_term    | varchar(255) | YES  |     | NULL              |                                               |
| search_results | int          | YES  |     | NULL              |                                               |
| times_searched | int          | YES  |     | NULL              |                                               |
| created_at     | timestamp    | YES  |     | CURRENT_TIMESTAMP | DEFAULT_GENERATED on update CURRENT_TIMESTAMP |
| updated_at     | timestamp    | YES  |     | NULL              |                                               |
+----------------+--------------+------+-----+-------------------+-----------------------------------------------+
6 rows in set (0.00 sec)
```

**Comment by royappa** [comment]
For now I just commented out all of ./resources/views/layouts/analytics.blade.php with {{-- and --}} which shows the site's home page, so this is not urgent now, we can return to Google Analytics later.

**Comment by d9it** [comment]
That's great, we will fix it in the next update.

Thanks.
