### ISSUE TITLE
Missing tables from migrations

### ISSUE THREAD

**Issue by inghamn** [sarapis/orservices#2]
When installing a fresh instance, without loading the NYC data, the migrations do not create the following tables:

* details
* organizations
* phones
* taxonomy
* schedule

**Comment by loveisbluenova** [comment]
There is sql file for database.
https://github.com/sarapis/orservices/blob/master/database/update_nyc.sql
You can use sql file instead of migrations.
In future, we will update migrations for DB structure.

**Comment by loveisbluenova** [comment]
I made the script to migrate the tables, so this issue will not happen again.
