### ISSUE TITLE
"Share" options are not intuitive

### ISSUE THREAD

**Issue by KM-Hanson** [sarapis/orservices#20]
Clicking the "share" button brings up a pop-up screen with different options for how to share. The range of options is confusing.

Some of the options are helpful and straightforward (email, Facebook, Twitter). 

Others are confusing - one is a link to support BLM (which is wonderful but does not make sense in this context as it is not an avenue to share the data). 

Snapchat is another option shown.... though you can't even make out the wording on that option.

![Screen Shot 2020-09-11 at 5 05 47 PM](https://user-images.githubusercontent.com/58799043/92973152-88a0f680-f451-11ea-8965-8bbd52be13fe.png)

**Comment by devinbalkind** [comment]
We'll fix

**Comment by devinbalkind** [comment]
The latest code make it easy for administrators to integrate their own ShareThis accounts and configure the share options via that interface. I'm closing this out. Let me know if you have further issues. Thanks!
