### ISSUE TITLE
Provide a supported search linked to the database?

### ISSUE THREAD

**Issue by KM-Hanson** [sarapis/orservices#22]
Is there a way to add support for a user as they search for services? The feedback that we have received is that many users don't know what words then can use to search, may not know what types of services are present in the database, and generally don't know what to search for unless they are a community health worker or a frequent site user.

![Screen Shot 2020-09-18 at 2 29 47 PM](https://user-images.githubusercontent.com/58799043/93632509-6fe99100-f9bb-11ea-9827-9ac17f483b87.png)

This is the type of user experience we were imagining as a "supported search", though the auto-populated suggestions would be best if they came from the database itself.

![Screen Shot 2020-09-18 at 2 30 29 PM](https://user-images.githubusercontent.com/58799043/93632633-a1625c80-f9bb-11ea-9556-9361faa6026d.png)

**Comment by devinbalkind** [comment]
Good idea. It'll go into a future work queue.

**Comment by devinbalkind** [comment]
This made it into the latest release so I'm closing this ticket.
