### ISSUE TITLE
Are the categories hard-coded?

### ISSUE THREAD

**Issue by KM-Hanson** [sarapis/orservices#23]
Can sites have control over (a) which categories are shown and (b) the wording and/or images used on each tile?

![Screen Shot 2020-09-18 at 2 31 55 PM](https://user-images.githubusercontent.com/58799043/93632743-d8387280-f9bb-11ea-8040-8a7d6fcf0c89.png)

**Comment by devinbalkind** [comment]
Yes, these categories can be edited in the admin. 

Categories without parents (highest level) are displayed in this section. 

Their icons can be configured from this page: http://orservices.sarapis.org/tb_taxonomy

![screencapture-orservices-sarapis-org-tb-taxonomy-2020-09-21-18_04_30](https://user-images.githubusercontent.com/444311/93826367-0e345b80-fc35-11ea-9aa8-e7967ae3b69f.png)

**Comment by KM-Hanson** [comment]
@devinbalkind Ok - thank you! Can you give guidelines on what size the image should be so that the tile spacing works well?

![Screen Shot 2020-09-23 at 9 45 21 PM](https://user-images.githubusercontent.com/58799043/94091426-33b49700-fde6-11ea-9041-2b6187d93e27.png)

**Comment by devinbalkind** [comment]
60px x 60px  - we'll add this guidance to the app.
