### ISSUE TITLE
Database dump in master

### ISSUE THREAD

**Issue by jorgerojasa** [sarapis/orservices#25]
I am so impressed with this great project! I am trying to deploy a local version of the master. Database upload section in the readme.md states "Create database and upload sql dump file from database/dump/latest_date.sql". Unfortunately, I cannot find any dump in the database folder. Latests date dumps from other branches cause a lot of errors. Artisan migration works well but without any data, the website does not load. Could you provide a sql dump for the master version? Thank you!

**Comment by devinbalkind** [comment]
We're looking into how to best deliver a sample dataset. Thanks and stay tuned!

**Comment by jorgerojasa** [comment]
Thank you for your reply. I think you are all doing a great job with this resource. I'll be in touch. If there anything I can do help, please let me know. I am mostly experienced in database management.

**Comment by devinbalkind** [comment]
Hi. We've updated the master branch with some new code and a sample database.

Please let me us know if you have any trouble deploying.

**Comment by jorgerojasa** [comment]
Thank you so much! We are going to deploy the branch and will get back with comments about our process.
