### ISSUE TITLE
"$email" must be an instance of SendGrid\Mail\From or a valid email address

### ISSUE THREAD

**Issue by rubywangruobin** [sarapis/orservices#30]
For suggest part in the nav bar, when trying to submit a suggestion, there reports an error even a valid email address is entered:

"$email" must be an instance of SendGrid\Mail\From or a valid email address

I entered:
eldercare organization
test
test
my personal email address
0000000

http://orservices.sarapis.org/suggest/create

**Comment by devinbalkind** [comment]
Got it. Posting a screenshot of the error here. 

![screencapture-orservices-sarapis-org-suggest-create-2020-11-02-15_25_03](https://user-images.githubusercontent.com/444311/97915533-9cfdc300-1d1f-11eb-8229-162dc3344310.png)

Thanks for logging it.

Will resolve.

**Comment by devinbalkind** [comment]
We've confirmed the issue is a missing SendGred email API key. We're adding the ability to add one's own API key in the backend. When we've done that we'll let you know.

**Comment by devinbalkind** [comment]
#31 Resolved this issue. Please let us know if more come up. 

Thanks!
