### ISSUE TITLE
Local Setup Issues

### ISSUE THREAD

**Issue by btmoore4** [sarapis/orservices#43]
Speaking with Devin, just wanted to create an issue where we could centralize some setup issues and questions that we are having. Hopefully will be able to document the process to allow quicker setup.

**Comment by btmoore4** [comment]
"Run git clone https://github.com/d9it/larable.git" This repo seems unavailable or now private? Is there a way to workaround or clone from another source?

**Comment by dangalan** [comment]
I'm think that command is just meant to the copy the repo where all the code is (some confirmation on this would be much appreciated). The other command  with "larable" in it (`chmod -R 755 ../larable`) just changes read, write, and executable status ([see here](https://laptrinhx.com/what-is-chmod-755-and-700-148178400/) - I ran `chmod -R 755 ../orservices` and everything looked ok. Git might read this change in file status as a change that needs to be uploaded which you can ignore with this command: `git config core.fileMode false` ([more explanation here](https://stackoverflow.com/questions/1580596/how-do-i-make-git-ignore-file-mode-chmod-changes)).

**Comment by dangalan** [comment]
Anyone else get this error trying to run locally:
`ErrorException
Trying to get property 'meta_filter_activate' of non-object (View: /Users/dangalan/Code/orservices/resources/views/layouts/filter.blade.php)`
Looks like `layout` in line 24 is null for some reason

**Comment by d9it** [comment]
> "Run git clone https://github.com/d9it/larable.git" This repo seems unavailable or now private? Is there a way to workaround or clone from another source?

The git repo url  is updated so use git clone https://github.com/sarapis/orservices.git.

**Comment by d9it** [comment]
> Anyone else get this error trying to run locally:
> `ErrorException Trying to get property 'meta_filter_activate' of non-object (View: /Users/dangalan/Code/orservices/resources/views/layouts/filter.blade.php)`
> Looks like `layout` in line 24 is null for some reason

The latest code is pushed into this repository and the updated database is 15022021.sql Url( https://github.com/sarapis/orservices/tree/master/database/dump). Take Pull from this repository & update the database with the latest, After that this issue will be fixed.

**Comment by dangalan** [comment]
> The latest code is pushed into this repository and the updated database is 15022021.sql Url( https://github.com/sarapis/orservices/tree/master/database/dump). Take Pull from this repository & update the database with the latest, After that this issue will be fixed.

I think all the `CREATE` statements in the dump files are unnecessary? Running `php artisan migrate` creates the tables right? Running `mysql -u root -p ORServices_local < database/dump/15022021.sql` throws the following for me: `ERROR 1050 (42S01) at line 30: Table 'accessibilities' already exists`.

**Comment by d9it** [comment]
> > The latest code is pushed into this repository and the updated database is 15022021.sql Url( https://github.com/sarapis/orservices/tree/master/database/dump). Take Pull from this repository & update the database with the latest, After that this issue will be fixed.
> 
> I think all the `CREATE` statements in the dump files are unnecessary? Running `php artisan migrate` creates the tables right? Running `mysql -u root -p ORServices_local < database/dump/15022021.sql` throws the following for me: `ERROR 1050 (42S01) at line 30: Table 'accessibilities' already exists`.
> 
> Updates:
> 
> 1. Ran the project locally without the DB dump, got the following error: `Trying to get property 'home_page_style' of non-object (View: /Users/dangalan/Code/orservices/resources/views/frontEnd/home.blade.php)`.
> 2. I then deleted the tables created by `php artisan migrate` and re-ran `mysql -u root -p ORServices_local < database/dump/15022021.sql` to create the tables that way and got the following error running locally: `Trying to get property 'active' of non-object (View: /Users/dangalan/Code/orservices/resources/views/layouts/style.blade.php)`.
> 
> Seems like both the migration and the dump contain something required to render the frontend? Would getting rid of any duplicated `CREATE` statements in the latest dump file resolve this issue?

The code is updated now. If you are using SQL dump file so don't use "php artisan migrate".

**Comment by devinbalkind** [comment]
I think was a success - yes!? If so I'll close the issue.

**Comment by btmoore4** [comment]
Correct, yes can close
