### ISSUE TITLE
Fatal Error Searching by Find Services Near an Address

### ISSUE THREAD

**Issue by DanielleDorot** [sarapis/orservices#6]
When searching by an address on both address search bars the following page with errors appears:  FatalThrowableError (see below)

![image](https://user-images.githubusercontent.com/47256278/52142842-d7589e80-2627-11e9-9650-81b20bbeff0f.png)

![inkedside bar search address](https://user-images.githubusercontent.com/47256278/52143022-79788680-2628-11e9-9403-041e46978a66.jpg)

![inked find services near an address](https://user-images.githubusercontent.com/47256278/52143023-79788680-2628-11e9-9935-0e9eb35efde3.jpg)

**Comment by devinbalkind** [comment]
Nice issue. We needed a new API key. Issue should be resolved now. Please let  us know if it works or doesn't and we can close the issue. Thank you.

**Comment by DanielleDorot** [comment]
It works now. Thank you.
