### ISSUE TITLE
Broken link to template on homepage

### ISSUE THREAD

**Issue by JordanLyons** [sarapis/orservices#9]
The link with the text "AirTable Open Referral Template" on the homepage is broken: https://airtable.com/universe/expTMdQFD5r9G6V9Y/open-referral-human-services-template

Should it really point to this? https://airtable.com/universe/expwt9yr65lFGUJAr/open-referral-directory-v20

**Comment by devinbalkind** [comment]
This will be resolved in the update.

**Comment by devinbalkind** [comment]
Thanks - changes made.
